#!/bin/sh

INSTALL_MODE=0
if [ -r /tmp/vlab-vnc ]; then
  INSTALL_MODE="$(cat < /tmp/vlab-vnc)"
fi
rm -f /tmp/vlab-vnc

systemctl daemon-reload

if [ "$INSTALL_MODE" = "1" ]; then
  systemctl enable vlab-vnc.service
  iptables -D INPUT ! -i lo ! -s 172.31.0.2 -p tcp --dport 5900 -j DROP >/dev/null 2>&1
  iptables -I INPUT ! -i lo ! -s 172.31.0.2 -p tcp --dport 5900 -j DROP
  iptables-save > /etc/iptables/rules.v4
fi
