#!/bin/sh

INSTALL_MODE=0
if [ -r /tmp/vlab-vnc ]; then
  INSTALL_MODE="$(cat < /tmp/vlab-vnc)"
fi
rm -f /tmp/vlab-vnc

if [ "$INSTALL_MODE" = "1" ]; then
  iptables -D INPUT ! -i lo ! -s 172.31.0.2 -p tcp --dport 5900 -j DROP >/dev/null 2>&1
  iptables -I INPUT ! -i lo ! -s 172.31.0.2 -p tcp --dport 5900 -j DROP
  ip6tables -D INPUT ! -i lo -p tcp --dport 5900 -j DROP >/dev/null 2>&1
  ip6tables -I INPUT ! -i lo -p tcp --dport 5900 -j DROP
  iptables-save > /etc/iptables/rules.v4
  ip6tables-save > /etc/iptables/rules.v6
fi
