#!/bin/sh
set -e

case "$1" in
  install)
    echo 1 > /tmp/vlab-vnc
    ;;
  upgrade|abort-upgrade)
    rm -f /tmp/vlab-vnc
    ;;
  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 0
    ;;
esac
#DEBHELPER#
exit 0
