#!/bin/sh
set -e

PACKAGE=vlab-vnc

case "$1" in
  install)
    dpkg-divert --package "$PACKAGE" --divert /etc/lightdm/lightdm.conf.dpkg-divert --add /etc/lightdm/lightdm.conf
    ;;
  upgrade|abort-upgrade)
    ;;
  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 0
    ;;
esac
#DEBHELPER#
exit 0
