#!/bin/sh
set -e

PACKAGE=vlab-earlyoom

case "$1" in
  install)
    dpkg-divert --package "$PACKAGE" --divert /etc/default/earlyoom.dpkg-divert --add /etc/default/earlyoom
    echo 1 > /tmp/vlab-earlyoom
    ;;
  upgrade|abort-upgrade)
    rm -f /tmp/vlab-earlyoom
    ;;
  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 0
    ;;
esac
#DEBHELPER#
exit 0
