#!/bin/sh
set -e

PACKAGE=pve-lxc-btrfs

case "$1" in
  install)
    dpkg-divert --package "$PACKAGE" --divert /usr/sbin/mkfs.ext4.dpkg-divert --rename --add /usr/sbin/mkfs.ext4
    dpkg-divert --package "$PACKAGE" --divert /usr/sbin/resize2fs.dpkg-divert --rename --add /usr/sbin/resize2fs
    ;;
  upgrade)
    if [ "$(dpkg-divert --listpackage /usr/sbin/resize2fs 2>/dev/null)" != "$PACKAGE" ]; then
      dpkg-divert --package "$PACKAGE" --divert /usr/sbin/resize2fs.dpkg-divert --rename --add /usr/sbin/resize2fs
    fi
    ;;
  abort-upgrade)
    ;;
  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 0
    ;;
esac
#DEBHELPER#
exit 0
