#!/bin/bash

# Vlab VNC wrapper script
: ${DISPLAY:=":0"} ${USERID:=$(id -u)}
DISPLAYNUMBER="${DISPLAY##*:}"
COOKIE="$(/usr/bin/mcookie)"
HOST="$(uname -n)"
USERNAME="$(id -nu $USERID)"
eval USERHOME=~${USERNAME}
VNCIDENT="$HOST:$DISPLAYNUMBER"

if [ -x "$USERHOME/.vnc/xstartup" ]; then
  XSTARTUP="$USERHOME/.vnc/xstartup"
else
  XSTARTUP="/etc/vlab/Xvnc-session"
fi

if [ "$1" = "stop" ]; then
  exec vncserver -kill "$DISPLAY"
fi

# Load resolution settings
GEOMETRY="1366x768"
GEOMETRYFILE="$USERHOME/.vnc/geometry"
if [ -r "$GEOMETRYFILE" ]; then
  GEOMETRYDATA="$(< "$GEOMETRYFILE")"
  if [[ "$GEOMETRYDATA" =~ ^[0-9]+x[0-9]+$ ]]; then
    GEOMETRY="$GEOMETRYDATA"
  fi
fi

xauth -f "$USERHOME/.Xauthority" source - << EOF
add $VNCIDENT . $COOKIE
add $HOST/unix:$DISPLAYNUMBER . $COOKIE
EOF

# Change to user directory
cd "$USERHOME"
mkdir -p .vnc

# Set locales
LANG=C.UTF-8
LC_ALL=C.UTF-8
. /etc/default/locale
export LANG LC_ALL

"$XSTARTUP" > ".vnc/$VNCIDENT.log" 2>&1 &
exec Xvnc "$DISPLAY" -desktop "$VNCIDENT ($USERNAME)" \
  -auth "$USERHOME/.Xauthority" -SecurityTypes None \
  -geometry "$GEOMETRY" -depth 16 -rfbport 5900 -pn \
  -fp /usr/X11R6/lib/X11/fonts/Type1/,/usr/X11R6/lib/X11/fonts/Speedo/,/usr/X11R6/lib/X11/fonts/misc/,/usr/X11R6/lib/X11/fonts/75dpi/,/usr/X11R6/lib/X11/fonts/100dpi/,/usr/share/fonts/X11/misc/,/usr/share/fonts/X11/Type1/,/usr/share/fonts/X11/75dpi/,/usr/share/fonts/X11/100dpi/ -co /etc/X11/rgb "$@"
