name: build

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Build packages
      run: |
        ./build.sh

    - name: Deploy to Vlab
      if: "github.repository == 'USTC-vlab/deb' && github.ref == 'refs/heads/master'"
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -p 179 vlab.ustc.edu.cn >> ~/.ssh/known_hosts
        rsync -e 'ssh -p 179' -rlptvz --delete build/ root@vlab.ustc.edu.cn:/
